"""empty message

Revision ID: 17575c8f4086
Revises: eff0ff927d90
Create Date: 2022-11-24 19:13:46.678280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17575c8f4086'
down_revision = 'eff0ff927d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
